<?php
session_start();
if (!isset($_SESSION['username'])) {
  header("Location: login.php");
  exit();
}
$username = $_SESSION['username'];
?>
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Leave Calendar</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>
<body class="bg-gray-50 text-gray-800 min-h-screen flex">

  <!-- Sidebar -->
  <aside class="hidden md:block w-64 bg-white shadow-md border-r">
    <?php include 'sidebar.php'; ?>
  </aside>

  <!-- Main content -->
  <main class="flex-1 flex flex-col p-6">

    <!-- Topbar / Header -->
    <header class="mb-6">
      <h2 class="text-2xl font-semibold flex items-center gap-2">📅 Leave Calendar</h2>
    </header>

    <!-- Month Selector -->
    <section class="mb-6">
      <label for="monthSelect" class="block font-semibold mb-1">Select Month:</label>
      <input type="month" id="monthSelect" class="border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
    </section>

    <!-- Calendar Container -->
    <section id="calendarContainer" class="grid grid-cols-7 gap-2 mb-6">
      <!-- Calendar will be generated by JavaScript -->
    </section>

    <!-- Info Section -->
    <section class="grid grid-cols-1 md:grid-cols-3 gap-6">

      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-lg font-semibold mb-3 flex items-center gap-2">📌 Features</h3>
        <ul class="list-disc list-inside space-y-1 text-sm">
          <li><strong>Select Month:</strong> View and manage leave days.</li>
          <li><strong>Mark Leave Days:</strong> Click to mark full-day leave. Right-click for half-day (coming soon).</li>
          <li><strong>Public Holidays:</strong> Will auto-highlight in green (coming soon).</li>
          <li><strong>Tooltips:</strong> Hover to view leave type (coming soon).</li>
        </ul>
      </div>

      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-lg font-semibold mb-3 flex items-center gap-2">📅 Legend</h3>
        <ul class="space-y-2 text-sm">
          <li class="flex items-center gap-2">
            <span class="w-5 h-5 rounded-sm bg-red-500 inline-block"></span> Leave Day
          </li>
          <li class="flex items-center gap-2">
            <span class="w-5 h-5 rounded-sm bg-blue-500 inline-block"></span> Weekend
          </li>
          <li class="flex items-center gap-2">
            <span class="w-5 h-5 rounded-sm bg-green-500 inline-block"></span> Public Holiday
          </li>
          <li class="flex items-center gap-2">
            <span class="w-5 h-5 rounded-sm bg-orange-500 inline-block"></span> Half-Day
          </li>
        </ul>
      </div>

      <div class="bg-white p-4 rounded-lg shadow">
        <h3 class="text-lg font-semibold mb-3 flex items-center gap-2">📝 Notes</h3>
        <ul class="list-disc list-inside space-y-1 text-sm">
          <li>This calendar is for personal tracking unless shared with your manager.</li>
          <li>Always submit official leave through the HR portal.</li>
        </ul>
      </div>

    </section>
  </main>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const monthSelect = document.getElementById('monthSelect');
      const calendarContainer = document.getElementById('calendarContainer');
      
      // Set default month to current month
      const today = new Date();
      const currentMonth = today.getFullYear() + '-' + String(today.getMonth() + 1).padStart(2, '0');
      monthSelect.value = currentMonth;
      
      // Generate calendar when month changes
      monthSelect.addEventListener('change', generateCalendar);
      
      // Initial calendar generation
      generateCalendar();
      
      function generateCalendar() {
        const [year, month] = monthSelect.value.split('-').map(Number);
        const firstDay = new Date(year, month - 1, 1);
        const lastDay = new Date(year, month, 0);
        const daysInMonth = lastDay.getDate();
        const startingDay = firstDay.getDay(); // 0 (Sunday) to 6 (Saturday)
        
        // Clear previous calendar
        calendarContainer.innerHTML = '';
        
        // Add day headers
        const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        days.forEach(day => {
          const dayHeader = document.createElement('div');
          dayHeader.className = 'text-center font-semibold py-2 bg-gray-100 rounded';
          dayHeader.textContent = day;
          calendarContainer.appendChild(dayHeader);
        });
        
        // Add empty cells for days before the first day of the month
        for (let i = 0; i < startingDay; i++) {
          const emptyCell = document.createElement('div');
          emptyCell.className = 'h-16 bg-gray-50 rounded';
          calendarContainer.appendChild(emptyCell);
        }
        
        // Add day cells
        for (let day = 1; day <= daysInMonth; day++) {
          const date = new Date(year, month - 1, day);
          const isWeekend = date.getDay() === 0 || date.getDay() === 6;
          const isToday = today.getDate() === day && 
                          today.getMonth() === month - 1 && 
                          today.getFullYear() === year;
          
          const dayCell = document.createElement('div');
          dayCell.className = `h-16 p-1 border rounded cursor-pointer transition-colors ${isWeekend ? 'bg-blue-100' : 'bg-white'} ${isToday ? 'border-2 border-blue-500' : ''}`;
          
          const dayNumber = document.createElement('div');
          dayNumber.className = 'text-right font-medium text-sm';
          dayNumber.textContent = day;
          dayCell.appendChild(dayNumber);
          
          // Add click event to mark leave days
          dayCell.addEventListener('click', function() {
            if (this.classList.contains('bg-red-100')) {
              this.classList.remove('bg-red-100');
            } else {
              this.classList.remove('bg-white', 'bg-blue-100');
              this.classList.add('bg-red-100');
            }
          });
          
          // Add right click event for half-day (coming soon)
          dayCell.addEventListener('contextmenu', function(e) {
            e.preventDefault();
            if (this.classList.contains('bg-orange-100')) {
              this.classList.remove('bg-orange-100');
            } else {
              this.classList.remove('bg-white', 'bg-blue-100', 'bg-red-100');
              this.classList.add('bg-orange-100');
            }
          });
          
          calendarContainer.appendChild(dayCell);
        }
      }
    });
  </script>
</body>
</html>